// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: basic/v1/uuid.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GenerateUuidRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GenerateUuidRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenerateUuidRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GenerateUuidRequestMultiError, or nil if none found.
func (m *GenerateUuidRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GenerateUuidRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	if len(errors) > 0 {
		return GenerateUuidRequestMultiError(errors)
	}

	return nil
}

// GenerateUuidRequestMultiError is an error wrapping multiple validation
// errors returned by GenerateUuidRequest.ValidateAll() if the designated
// constraints aren't met.
type GenerateUuidRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenerateUuidRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenerateUuidRequestMultiError) AllErrors() []error { return m }

// GenerateUuidRequestValidationError is the validation error returned by
// GenerateUuidRequest.Validate if the designated constraints aren't met.
type GenerateUuidRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenerateUuidRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenerateUuidRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenerateUuidRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenerateUuidRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenerateUuidRequestValidationError) ErrorName() string {
	return "GenerateUuidRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GenerateUuidRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenerateUuidRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenerateUuidRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenerateUuidRequestValidationError{}

// Validate checks the field values on GenerateUuidResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GenerateUuidResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenerateUuidResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GenerateUuidResponseMultiError, or nil if none found.
func (m *GenerateUuidResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GenerateUuidResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Value

	if len(errors) > 0 {
		return GenerateUuidResponseMultiError(errors)
	}

	return nil
}

// GenerateUuidResponseMultiError is an error wrapping multiple validation
// errors returned by GenerateUuidResponse.ValidateAll() if the designated
// constraints aren't met.
type GenerateUuidResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenerateUuidResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenerateUuidResponseMultiError) AllErrors() []error { return m }

// GenerateUuidResponseValidationError is the validation error returned by
// GenerateUuidResponse.Validate if the designated constraints aren't met.
type GenerateUuidResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenerateUuidResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenerateUuidResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenerateUuidResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenerateUuidResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenerateUuidResponseValidationError) ErrorName() string {
	return "GenerateUuidResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GenerateUuidResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenerateUuidResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenerateUuidResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenerateUuidResponseValidationError{}
