// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.15.8
// source: basic/v1/uuid.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUuidGenerate = "/basic.v1.Uuid/Generate"

type UuidHTTPServer interface {
	Generate(context.Context, *GenerateUuidRequest) (*GenerateUuidResponse, error)
}

func RegisterUuidHTTPServer(s *http.Server, srv UuidHTTPServer) {
	r := s.Route("/")
	r.POST("/uuid/generate", _Uuid_Generate0_HTTP_Handler(srv))
}

func _Uuid_Generate0_HTTP_Handler(srv UuidHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GenerateUuidRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUuidGenerate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Generate(ctx, req.(*GenerateUuidRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GenerateUuidResponse)
		return ctx.Result(200, reply)
	}
}

type UuidHTTPClient interface {
	Generate(ctx context.Context, req *GenerateUuidRequest, opts ...http.CallOption) (rsp *GenerateUuidResponse, err error)
}

type UuidHTTPClientImpl struct {
	cc *http.Client
}

func NewUuidHTTPClient(client *http.Client) UuidHTTPClient {
	return &UuidHTTPClientImpl{client}
}

func (c *UuidHTTPClientImpl) Generate(ctx context.Context, in *GenerateUuidRequest, opts ...http.CallOption) (*GenerateUuidResponse, error) {
	var out GenerateUuidResponse
	pattern := "/uuid/generate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUuidGenerate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
