// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.4

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type UploadHTTPServer interface {
	StreamUploadFile(context.Context, *StreamUploadFileRequest) (*StreamUploadFileReply, error)
}

func RegisterUploadHTTPServer(s *http.Server, srv UploadHTTPServer) {
	r := s.Route("/")
	r.PUT("/file/stream", _Upload_StreamUploadFile0_HTTP_Handler(srv))
}

func _Upload_StreamUploadFile0_HTTP_Handler(srv UploadHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StreamUploadFileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/upload.v1.Upload/StreamUploadFile")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StreamUploadFile(ctx, req.(*StreamUploadFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StreamUploadFileReply)
		return ctx.Result(200, reply)
	}
}

type UploadHTTPClient interface {
	StreamUploadFile(ctx context.Context, req *StreamUploadFileRequest, opts ...http.CallOption) (rsp *StreamUploadFileReply, err error)
}

type UploadHTTPClientImpl struct {
	cc *http.Client
}

func NewUploadHTTPClient(client *http.Client) UploadHTTPClient {
	return &UploadHTTPClientImpl{client}
}

func (c *UploadHTTPClientImpl) StreamUploadFile(ctx context.Context, in *StreamUploadFileRequest, opts ...http.CallOption) (*StreamUploadFileReply, error) {
	var out StreamUploadFileReply
	pattern := "/file/stream"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/upload.v1.Upload/StreamUploadFile"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
