// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.4

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type ShortLinkHTTPServer interface {
	GenerateShortUrl(context.Context, *GenerateShortUrlRequest) (*GenerateShortUrlReply, error)
	TransformLongUrl(context.Context, *TransformLongUrlRequest) (*TransformLongUrlReply, error)
}

func RegisterShortLinkHTTPServer(s *http.Server, srv ShortLinkHTTPServer) {
	r := s.Route("/")
	r.POST("/generate/short_url", _ShortLink_GenerateShortUrl0_HTTP_Handler(srv))
	r.POST("/transform/long_url", _ShortLink_TransformLongUrl0_HTTP_Handler(srv))
}

func _ShortLink_GenerateShortUrl0_HTTP_Handler(srv ShortLinkHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GenerateShortUrlRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/services.link.v1.ShortLink/GenerateShortUrl")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GenerateShortUrl(ctx, req.(*GenerateShortUrlRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GenerateShortUrlReply)
		return ctx.Result(200, reply)
	}
}

func _ShortLink_TransformLongUrl0_HTTP_Handler(srv ShortLinkHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TransformLongUrlRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/services.link.v1.ShortLink/TransformLongUrl")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TransformLongUrl(ctx, req.(*TransformLongUrlRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TransformLongUrlReply)
		return ctx.Result(200, reply)
	}
}

type ShortLinkHTTPClient interface {
	GenerateShortUrl(ctx context.Context, req *GenerateShortUrlRequest, opts ...http.CallOption) (rsp *GenerateShortUrlReply, err error)
	TransformLongUrl(ctx context.Context, req *TransformLongUrlRequest, opts ...http.CallOption) (rsp *TransformLongUrlReply, err error)
}

type ShortLinkHTTPClientImpl struct {
	cc *http.Client
}

func NewShortLinkHTTPClient(client *http.Client) ShortLinkHTTPClient {
	return &ShortLinkHTTPClientImpl{client}
}

func (c *ShortLinkHTTPClientImpl) GenerateShortUrl(ctx context.Context, in *GenerateShortUrlRequest, opts ...http.CallOption) (*GenerateShortUrlReply, error) {
	var out GenerateShortUrlReply
	pattern := "/generate/short_url"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/services.link.v1.ShortLink/GenerateShortUrl"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ShortLinkHTTPClientImpl) TransformLongUrl(ctx context.Context, in *TransformLongUrlRequest, opts ...http.CallOption) (*TransformLongUrlReply, error) {
	var out TransformLongUrlReply
	pattern := "/transform/long_url"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/services.link.v1.ShortLink/TransformLongUrl"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
